name:                json-ld
version:             0.1.0.0
github:              "agentultra/json-ld"
license:             MIT
author:              "James King"
maintainer:          "james@agentultra.com"
copyright:           "2018 James King"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category: Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/agentultra/json-ld#readme>

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

dependencies:
  - base >= 4.7 && < 5
  - protolude

library:
  source-dirs: src

tests:
  json-ld-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - json-ld
      - QuickCheck
      - hspec
      - quickcheck-instances
